camel.main.name = DemoJDBCMySQL
# Properties for database connection
database.host={{env:DB_HOST}}
database.name={{env:DB_NAME}}
database.user={{env:DB_USER}}
database.pass={{env:DB_PASS}}
# Properties for HTTP Server
server.host=0.0.0.0
server.port=9000


# Config maps
# Properties for database connection