camel.main.name = DemoJDBCMySQL
# Properties for database connection
database.host=mysql
database.name=test
database.user=camel_user
database.pass=camel_pass
# Properties for HTTP Server
server.host=0.0.0.0
server.port=8081
